#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm) //the sonar sensor is measured in cm
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#include "header.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Wait for Light -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to drive in a straight line until reaching an obstacle, the      *|
|*		robot will then turn 90 degrees and continue driving.																						*|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*                                                                                                    *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 8     lightSensor         VEX Light Sensor      Mounted facing up                 *|
\*-----------------------------------------------------------------------------------------------4246-*/

void reset_encoder(){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}

void turn(int deg,bool leftRight){
	while(abs(SensorValue[leftEncoder]) < deg*TURNCONST && vexRT[Btn7U] == 0)
    {
		if(leftRight){
		motor[rightMotor] = POWER;		  // Motor is stop
		motor[leftMotor]  = -POWER;
		}
		else{
				motor[rightMotor] = -POWER;		  // Motor is stop
				motor[leftMotor]  = POWER;
		}
	}
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	reset_encoder();
	wait1Msec(2000);					          // Robot waits for 2000 milliseconds before executing program
		while(SensorValue(lightSensor) < 350)
		{
			if(SensorValue(sonarSensor) > 30  || SensorValue(sonarSensor) == -1){
			motor[rightMotor] = POWER;			          // Motor on port2 is run at half (63) power forward
			motor[leftMotor]  = POWER;
			}
			else{
				reset_encoder();
				turn(90,true);
			}
		}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
