#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#include "header.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:																																													*|
|*  This program uses the Shaft Encoders to move forward for a certain distance.                      *|
|*  Robot runs for loop for the first few turns then it goes by code till it stops at end.            *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/
void reset_encoder(){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}
void drive_forward(){
	while(abs(SensorValue[leftEncoder]) < BASEROTATION && vexRT[Btn7U] == 0)
  {
    //...Move Forward
    motor[rightMotor] = POWER;
    motor[leftMotor] = POWER;
    wait1Msec(2000);
  }
}
void drive_short_forward(){
	while(abs(SensorValue[leftEncoder]) < BASEROTATION && vexRT[Btn7U] == 0)
  {
    //...Move Forward
    motor[rightMotor] = POWER;
    motor[leftMotor] = POWER;
    wait1Msec(5000);
  }
}
void drive_long_forward(){
	while(abs(SensorValue[leftEncoder]) < BASEROTATION && vexRT[Btn7U] == 0)
  {
    //...Move Forward
    motor[rightMotor] = POWER;
    motor[leftMotor] = POWER;
    wait1Msec(6000);
  }
}
void turn(int deg,bool leftRight){
	while(abs(SensorValue[leftEncoder]) < deg*TURNCONST && vexRT[Btn7U] == 0)
    {
		if(leftRight){
		motor[rightMotor] = POWER;		  // Motor is stop
		motor[leftMotor]  = -POWER;
		}
		else{
				motor[rightMotor] = -POWER;		  // Motor is stop
				motor[leftMotor]  = POWER;
		}
	}
}
void stop_rob(){
	motor[rightMotor] = 0;		  // Motor is stop
	motor[leftMotor]  = 0;
	wait1Msec(500);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

	while(vexRT[Btn7U] == 0)
	{
	   for(int a = 0; a < 4; a = a + 1 ){
	      reset_encoder();
			  drive_forward();
			  stop_rob();
			  reset_encoder();
			  if(a=1 || a=3){
			  turn(90,true);
				}
				else{
					turn(90,false);
				}
			  stop_rob();
			  reset_encoder();
			  drive_short_forward();
			  stop_rob();
			  reset_encoder();
			  if(a=1 || a= 3){
			  	turn(90,true);
				}
				else{
					turn(90,false);
				}
				stop_rob();
	   }//fyrri hluti af braut
	   for(int a = 0; a < 5; a = a + 1 ){
	      reset_encoder();
	      if(a=0){
			  	drive_long_forward();
				}
				else if(a=1 || a=3){
			  	drive_forward();
				}
				else if(a=2 || a=4){
			  	drive_short_forward();
				}
			  stop_rob();
			  reset_encoder();
			  if(a=0 || a=1 || a=2){
			  	turn(90,true);
				}
				else{
					turn(90,false);
				}
			  stop_rob();
	   }//seinni hluti af braut
	  reset_encoder();
	  drive_forward();
	  stop_rob();//endar  lokapunkt
	}
}
