#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#include "header.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|                                     *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:																																													*|
|*			Robot follows the line, stops when sees object, picks it up and bool becomes true.						*|
|*			Robot follows line again but when sees object he only lets go and breaks.											*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/
void resetEncoder(){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
}
void armDown(){
	motor[armMotor] = 40;
	wait1Msec(1000);
	motor[armMotor] = 0;
	wait1Msec(1000);
}
void armUp(){
	motor[armMotor] = -40;
	wait1Msec(2000);
	motor[armMotor] = 0;
	wait1Msec(1000);
}
void stopMotors(){
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
}
void clawClose(){
	motor[clawMotor] = -60;
	wait1Msec(1000);
	motor[clawMotor] = 0;
	wait1Msec(1000);
}
void clawOpen(){
	motor[clawMotor] = 60;
	wait1Msec(1000);
	motor[clawMotor] = 0;
	wait1Msec(1000);
}
/**Turn Robot**/
void turn(int deg,bool leftRight){
	while(abs(SensorValue[leftEncoder]) < deg*TURNCONST && vexRT[Btn7U] == 0)
    {
		if(leftRight){
		motor[rightMotor] = POWER;		  // Motor is stop
		motor[leftMotor]  = -POWER;
		}
		else{
				motor[rightMotor] = -POWER;		  // Motor is stop
				motor[leftMotor]  = POWER;
		}
	}
}
bool endtask = false;

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

	while(vexRT[Btn7U] == 0)
	{
		// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+
		displayLCDCenteredString(0, "LEFT  CNTR  RGHT");        //  Display   |
		displayLCDPos(1,0);                                     //  Sensor    |
		displayNextLCDNumber(SensorValue(lineFollowerLEFT));    //  Readings  |
		displayLCDPos(1,6);                                     //  to LCD.   |
		displayNextLCDNumber(SensorValue(lineFollowerCENTER));  //            |
		displayLCDPos(1,12);                                    //  L  C  R   |
		displayNextLCDNumber(SensorValue(lineFollowerRIGHT));   //  x  x  x   |
		// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+

		// RIGHT sensor sees dark:
		if(SensorValue(lineFollowerRIGHT) > THRESHOLD)
		{
			// counter-steer right:
			motor[leftMotor]  = SIDEPOWER;
			motor[rightMotor] = SIDEMINPOWER;
		}
		// CENTER sensor sees dark:
		if(SensorValue(lineFollowerCENTER) > THRESHOLD2)
		{
			// go straight
			motor[leftMotor]  = POWER;
			motor[rightMotor] = POWER;
		}
		// LEFT sensor sees dark:
		if(SensorValue(lineFollowerLEFT) > THRESHOLD)
		{
			// counter-steer left:
			motor[leftMotor]  = SIDEMINPOWER;
			motor[rightMotor] = SIDEPOWER;
		}
		else if(SensorValue(sonarSensor) < 15 || SensorValue(sonarSensor) == -1)
		{
			stopMotors();
			if(endtask){
			clawOpen();
			break;
			}
			clawOpen();
			armDown();
			clawClose();
			armUp();
			resetEncoder();
			turn(150,true);
			endtask = true;
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
