#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|                                                                        *|
|*
			Program drives robot forwards half a metre, back half a metre, then 1 metre forward etc..
			until it has reached a distance of 2,5 metres forwards and backwards.
*|
\*-----------------------------------------------------------------------------------------------4246-*/

void drive_forward(int K){
	motor[rightMotor] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 127;	  // Motor on port3 is run at full (127) power forward
	wait1Msec(1100 * K);
}
void drive_back(int K){
	motor[rightMotor] = -127;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = -127;	  // Motor on port3 is run at full (127) power forward
	wait1Msec(1100 * K);
}
void turn_right(){
	motor[rightMotor] = -127;		  // Motor turns
	motor[leftMotor]  = 127;
	wait1Msec(925);
}
void turn_left(){
	motor[rightMotor] = 127;		  // Motor turns
	motor[leftMotor]  = -127;
	wait1Msec(925);
}
void fix_tilt(){
		  // Motor turns a little to correct direction
	motor[leftMotor]  = -100;
	wait1Msec(55);
}
void stop_rob(){
	motor[rightMotor] = 0;		  // Motor is stop
	motor[leftMotor]  = 0;
	wait1Msec(500);
}


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  //int distance = 1;
	wait1Msec(1000);						// Robot waits for 1000 milliseconds before executing program
	for(int i = 1;i < 6; i++) {
		drive_forward(i);//drives the distance forward
		stop_rob();//stops so it does not change direction
		fix_tilt();//corrects a little the direction of the bot
		stop_rob();
		drive_back(i);//drives back to starting point
		stop_rob();
		fix_tilt();
		stop_rob();
	}
}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
