#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorServoContinuousRotation, openLoop)
#include "header.h"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                             	    - Triple Sensor Line Tracking -                                   *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses 3 VEX Line Follower Sensors to track a black line on a light(er) surface.       *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    Program instructs robot to follow a line using the line follower sensors, by reading the values *|
|*		of the sensors.																																								  *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 1     lineFollowerRIGHT   VEX Light Sensor      Front-right, facing down          *|
|*    Analog - Port 2     lineFollowerCENTER  VEX Light Sensor      Front-center, facing down         *|
|*    Analog - Port 3     lineFollowerLEFT    VEX Light Sensor      Front-left, facing down           *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);          // The program waits for 2000 milliseconds before continuing.

	  while(vexRT[Btn7U] == 0)
	  {
	    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+
	    displayLCDCenteredString(0, "LEFT  CNTR  RGHT");        //  Display   |
	    displayLCDPos(1,0);                                     //  Sensor    |
	    displayNextLCDNumber(SensorValue(lineFollowerLEFT));    //  Readings  |
	    displayLCDPos(1,6);                                     //  to LCD.   |
	    displayNextLCDNumber(SensorValue(lineFollowerCENTER));  //            |
	    displayLCDPos(1,12);                                    //  L  C  R   |
	    displayNextLCDNumber(SensorValue(lineFollowerRIGHT));   //  x  x  x   |
	    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -+

	    // RIGHT sensor sees dark:
	    if(SensorValue(lineFollowerRIGHT) > THRESHOLD)
	    {
	      // counter-steer right:
	      motor[leftMotor]  = 60;
	      motor[rightMotor] = -40;
	    }
	    // CENTER sensor sees dark:
	    if(SensorValue(lineFollowerCENTER) > THRESHOLD2)
	    {
	      // go straight
	      motor[leftMotor]  = POWER;
	      motor[rightMotor] = POWER;
	    }
	    // LEFT sensor sees dark:
	    if(SensorValue(lineFollowerLEFT) > THRESHOLD)
	    {
	      // counter-steer left:
	      motor[leftMotor]  = -40;
	      motor[rightMotor] = 60;
	    }
	    if(SensorValue(sonarSensor) <= 40){
				motor[rightMotor] = 0;
				motor[leftMotor]  = 0;
				motor[armMotor] = 20;
	    	wait1Msec(2500);
				wait1Msec(3000);
			}
	  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
